-- =========================================================
-- Module      : USART
-- Description : UART transmitter finite state machine.
--
--               This module transmits one 8-bit character
--               serially on the TxD output using a standard
--               UART frame:
--               - 1 start bit
--               - 8 data bits
--               - 1 stop bit
--
--               Transmission is synchronized using the BaudEn
--               pulse generated by the baud rate generator.
--
--               A transmission request is latched using the
--               StartTr input and cleared once transmission
--               begins.
--
-- Inputs:
--   Clk     : System clock
--   RAZ     : Active-low reset
--   StartTr : Transmission start request
--   BaudEn  : Baud rate enable pulse
--   DataIn  : 8-bit data to transmit
--
-- Outputs:
--   TxD     : Serial UART transmit line
--
-- Notes:
--   Data bits are transmitted LSB first, which matches the
--   standard UART convention.
--
-- Author     : Emre Bekci
-- =========================================================

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

entity USART is
    port(
        Clk, RAZ, StartTr, BaudEn : in  std_logic := '0';
        DataIn                    : in  std_logic_vector(7 downto 0);
        TxD                       : out std_logic
    );
end entity USART;

architecture behavior of USART is

    -- UART transmitter states
    type etat_type is (IDLE, START, DATA, STOP);

    -- Present and next state signals
    signal etat_present, etat_suivant : etat_type;

    -- Bit counter used during data transmission (0 to 7)
    signal compteur, compteur_suivant : unsigned(2 downto 0);

    -- Internal latched transmission request
    signal send_req : std_logic;

begin

    -- =====================================================
    -- State and register update process
    -- Handles:
    -- - reset
    -- - state register update
    -- - bit counter update
    -- - latching of transmission request
    -- =====================================================
    RE : process(Clk, RAZ)
    begin
        if RAZ = '0' then
            etat_present <= IDLE;
            compteur <= (others => '0');
            send_req <= '0';

        elsif rising_edge(Clk) then
            etat_present <= etat_suivant;
            compteur <= compteur_suivant;

            -- Latch transmission request when StartTr is asserted
            if StartTr = '1' then
                send_req <= '1';

            -- Clear request once transmission starts from IDLE
            elsif etat_present = IDLE and BaudEn = '1' and send_req = '1' then
                send_req <= '0';
            end if;
        end if;
    end process;

    -- =====================================================
    -- Next-state logic
    -- Determines UART state transitions and counter updates
    -- =====================================================
    FT : process(etat_present, BaudEn, compteur, send_req)
    begin
        etat_suivant <= etat_present;
        compteur_suivant <= compteur;

        case etat_present is

            -- Waiting for a transmission request
            when IDLE =>
                if send_req = '1' then
                    if BaudEn = '1' then
                        etat_suivant <= START;
                    end if;
                end if;

            -- Send start bit for one baud period
            when START =>
                if BaudEn = '1' then
                    etat_suivant <= DATA;
                end if;

            -- Send 8 data bits, one bit per baud pulse
            when DATA =>
                if BaudEn = '1' then
                    if compteur = to_unsigned(7, 3) then
                        compteur_suivant <= (others => '0');
                        etat_suivant <= STOP;
                    else
                        compteur_suivant <= compteur + 1;
                    end if;
                end if;

            -- Send stop bit for one baud period, then return to IDLE
            when STOP =>
                if BaudEn = '1' then
                    etat_suivant <= IDLE;
                end if;

        end case;
    end process;

    -- =====================================================
    -- Output logic (Moore machine)
    -- Defines the TxD output depending only on the current state
    -- =====================================================
    FS_moore : process(etat_present, DataIn, compteur)
    begin
        case etat_present is
            when IDLE =>
                TxD <= '1'; -- UART idle line is high

            when START =>
                TxD <= '0'; -- Start bit

            when DATA =>
                TxD <= DataIn(to_integer(compteur)); -- Transmit current bit (LSB first)

            when STOP =>
                TxD <= '1'; -- Stop bit
        end case;
    end process;

end architecture;